# Dockerfile-spring.template
# === Build stage ===
FROM maven:3.8.8-amazoncorretto-21 AS builder

WORKDIR /app

COPY ./generated/pom.xml .
COPY ./generated/src ./src

RUN mvn clean package -DskipTests

# === Run stage ===
FROM amazoncorretto:21-alpine
WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
