# Dockerfile-python.template
FROM python:3.12-slim

WORKDIR /app

# Install requirements
COPY generated/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY generated ./generated

EXPOSE 8080

ENV PYTHONPATH=/app/generated

CMD ["python", "-u", "-m", "openapi_server"]