services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: microsynth
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_ROOT_USERNAME: root
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d

volumes:
  mongo_data: